
language: objective-c
osx_image: xcode11.3

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8


before_install:
    - env
    - locale
    - gem install cocoapods --pre --no-document --quiet
    - gem install xcpretty --no-document --quiet
    - pod --version
    - pod setup --silent > /dev/null
    - pod repo update --silent
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail

    - echo Check if the library described by the podspec can be built
    - pod lib lint --allow-warnings

    - echo Build
    - xcodebuild clean build -workspace Example/FTMTableSectionModules.xcworkspace -scheme 'FTMTableSectionModules' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c

    - echo Build the Demo apps
    - xcodebuild clean build -workspace Example/FTMTableSectionModules.xcworkspace -scheme 'FTMTableSectionModules-Example' -configuration Debug -destination 'name=iPhone 8' | xcpretty -c

    - echo Run the tests
    - xcodebuild test -workspace Example/FTMTableSectionModules.xcworkspace -scheme 'FTMTableSectionModules-Example' -configuration Debug -destination 'name=iPhone 8' | xcpretty -c

after_success:
